# Generated by Django 2.2.3 on 2019-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('in_fridge', models.BooleanField()),
                ('season_start', models.DateField(db_index=True)),
                ('season_end', models.DateField(db_index=True)),
            ],
        ),
    ]
